### ISSUE TITLE
partytown-sandbox-sw.html Not Found on Nextjs

### ISSUE THREAD

**Issue by ronaiza-cardoso** [BuilderIO/partytown#31]
Hi, 👋.

I'm very excited to see this project going into prod mode, it is an amazing idea!

I've been unable to import the React version into our Nextjs@11, [I also tried with the vanilla version](https://github.com/ronaiza-cardoso/party-js-test/tree/with-vanilla-script), and didn't work as well. I've created a sample project using the basic Nextjs starter page as a demo.

Reproduction steps:

- [Clone the project](https://github.com/ronaiza-cardoso/party-js-test)
- install dependencies, including Partytown
- `yarn build:watch & yarn dev`
- when the project was initialized I was not able to see the Party on my console :(

Screenshots of those errors are below:

![image](https://user-images.githubusercontent.com/7999914/139434616-6f432afb-7479-4141-ba05-1c2746841c6f.png)

![image](https://user-images.githubusercontent.com/7999914/139434654-c86393b6-5e04-4450-91c7-4dae4597809a.png)

Seems that one `.html` is missing from the lib build.

![image](https://user-images.githubusercontent.com/7999914/139436270-c4b9f0ab-4f90-4bc8-9841-d94db670fe32.png)

I don't know if I'm missing some configuration, probably 😅 , but I can't for the life of my figure out what it might be. Have you ever seen this before or know what might be going on.

Thank you enormously in advance 🙇🏽‍♀️

**Comment by adamg-wix** [comment]
@ronaiza-cardoso  The same issue happens when you try to use the non-debug version. The file doesn't exist in the partytown lib folder : 
https://unpkg.com/browse/@builder.io/partytown@0.0.20/lib/

Got the same issue.

**Comment by ronaiza-cardoso** [comment]
@adamg-wix were you able to work around this issue?

**Comment by adamdbradley** [comment]
Thank you for the report. This should be fixed now in the latest release. Please reopen another issue if you continue to have issues.

**Comment by shailander** [comment]
Still facing the issue in the latest build @0.3.5
![Screenshot 2022-02-17 at 5 59 06 PM](https://user-images.githubusercontent.com/25870859/154482075-9b429214-8335-43ee-b345-229d00468d9e.png)
![Screenshot 2022-02-17 at 6 00 31 PM](https://user-images.githubusercontent.com/25870859/154482394-33a828d8-714d-49a1-9341-95b2679498c4.png)
![Screenshot 2022-02-17 at 6 01 05 PM](https://user-images.githubusercontent.com/25870859/154482412-67d086d2-520b-4c9c-916c-0d18c1931276.png)
